<?php

namespace Mission_locale\MainBundle\Repository;

/**
 * AppelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppelRepository extends \Doctrine\ORM\EntityRepository
{
    public function filter($avancement)
    {
        $qb = $this->createQueryBuilder('u')
            ->select('u')
            ->where('u.avancement = :avancement')
            ->orderBy('u.id')
            ->setParameter('avancement',$avancement);
        return $qb->getQuery()->getResult();
    }

    public function findByNumero($numero)
    {
        $qb = $this->createQueryBuilder('u')
            ->select('u')
            ->where('u.telephone = :telephone')
            ->setParameter('telephone',$numero);
        return $qb->getQuery()->getResult();
    }
}