<?php

namespace Mission_locale\MainBundle\Repository;

/**
 * QuiSommesNousRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuiSommesNousRepository extends \Doctrine\ORM\EntityRepository
{
}
