<?php

namespace Mission_locale\MainBundle\Repository;

/**
 * Sous_itemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SousItemRepository extends \Doctrine\ORM\EntityRepository
{
    public function getSousItem($slug)
    {
        $qb = $this->createQueryBuilder('u')
            ->select('u')
            ->from('MainBundle:Category', 'c')
            ->where('c.slug = :slug')
            ->setParameter('slug',$slug);

        return $qb->getQuery()->getResult();
    }
}
