<?php

namespace Mission_locale\AdminBundle\Entity;

/**
 * AgendaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgendaRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAgenda()
    {
        $qb = $this->createQueryBuilder('u')
            ->select('u');
        return $qb->getQuery()->getSingleResult();
    }
}
