<?php

namespace Mission_locale\AdminBundle\Entity;

/**
 * DocRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocRepository extends \Doctrine\ORM\EntityRepository
{
}
