admin_antenne:
    path: /
    defaults: { _controller: AdminBundle:Antenne:show }
antenne_add:
    path: /add
    defaults: { _controller: AdminBundle:Antenne:add }
antenne_edit:
    path: /{id}/edit
    defaults: { _controller: AdminBundle:Antenne:update }
    requirements:
                id: \d+
antenne_delete:
    path: /{id}/delete
    defaults: { _controller: AdminBundle:Antenne:delete }
    requirements:
            id: \d+

