admin_appel:
    path: /
    defaults: { _controller: AdminBundle:Appel:show }
appel_update:
    path: /{id}/update
    defaults: { _controller: AdminBundle:Appel:update }
    requirements:
        id: \d+
appel_delete:
    path: /{id}/delete
    defaults: { _controller: AdminBundle:Appel:delete }
    requirements:
        id: \d+