admin_parametre:
    path: /
    defaults: { _controller: AdminBundle:Admin:parametre }
admin_users:
    path: /users
    defaults: { _controller: AdminBundle:User:users }
delete_user:
    path: /{id}/user
    defaults: { _controller: AdminBundle:User:deleteUser }
    requirements:
                id: \d+
admin_mention_legal:
    path: /mention_legal
    defaults: { _controller: AdminBundle:Parametre:mention_legal}
admin_cgo:
    path: /cgo
    defaults: { _controller: AdminBundle:Parametre:cgo}
