<?php

namespace Mission_locale\MainBundle\Entity;

/**
 * EncartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EncartRepository extends \Doctrine\ORM\EntityRepository
{
}
