<?php

namespace Mission_locale\MainBundle\Entity;

/**
 * MentionLegalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MentionLegalRepository extends \Doctrine\ORM\EntityRepository
{
}
